# Totem Right (Slave)
CONFIG_ZMK_SPLIT=y

# Keine USB/Logging
CONFIG_ZMK_USB_LOGGING=n
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Basiswerte
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=3

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=300
