# Totem Left (Master)
CONFIG_ZMK_SPLIT=y

# USB & Logging
CONFIG_ZMK_USB_LOGGING=n
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# BT Power / Verbindungsparameter
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=3

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=300

# BLE Low Latency Settings (nur Master!)

CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400


# Keyboard Name
CONFIG_ZMK_KEYBOARD_NAME="Totem"
