CONFIG_ZMK_USB_LOGGING=n

CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y,


 # Default config
CONFIG_ZMK_KEYBOARD_NAME="Totem"
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=3

# ---- Low Latency BLE ----
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_SPLIT=y
CONFIG_BT_PERIPHERAL_PREF_MIN_CONN_INTERVAL=6   # 7.5 ms
CONFIG_BT_PERIPHERAL_PREF_MAX_CONN_INTERVAL=9   # 11.25 ms
CONFIG_BT_PERIPHERAL_PREF_SLAVE_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_BT_HID_INTERRUPT_PRIORITY=2
